# name: Deploy to Shared Hosting

# on:
#   push:
#     branches: [ "main" ]   # deploy only on main branch

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout repo
#       uses: actions/checkout@v3

#     - name: Install SSH Key
#       uses: webfactory/ssh-agent@v0.5.3
#       with:
#         ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

#     - name: Deploy to server
#       run: |
#         ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
#           cd ${{ secrets.SERVER_PATH }}
#           git pull origin main
#           composer install --no-dev --optimize-autoloader
#           php artisan migrate --force
#           php artisan optimize:clear
#           php artisan optimize
#         EOF

name: Deploy to BigRock Shared Hosting

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - run: php -v

      - name: Install composer dependencies
        run: |
            composer install --no-dev --optimize-autoloader
            npm install
            npm run build

      - name: Validate PHP & Composer
        run: |
          php -v
          composer --version

      - name: Install Node Dependencies and Build (Locally)
        run: |
          npm install
          npm run build
      - name: Clean upload folder
        run: |
          rm -rf node_modules .git .github tests

      - name: Create test file
        run: echo "Deployment Success" > deployment_test.txt

      - name: Upload files to BigRock via SSH/SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./"
          target: ${{ secrets.SERVER_PATH }}
          overwrite: true

